# Generated by Django 5.1.4 on 2024-12-09 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=50)),
                ('IsActive', models.BooleanField(default=True, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=50)),
                ('MiddleName', models.CharField(max_length=50, null=True)),
                ('LastName', models.CharField(max_length=50)),
                ('EmailID', models.EmailField(max_length=50)),
                ('ContactNo', models.CharField(max_length=10)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humanresource.department')),
            ],
        ),
    ]
