# Generated by Django 5.1.4 on 2024-12-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanresource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='MiddleName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
